config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :listings do
    resources :deposits, except: :index
  end

  resources :deposits, only: :index

  root 'pages#home'
  get '/contact' , to: 'pages#contact'
  get '/about' , to: 'pages#about'

  get '/help' , to: 'listings#help'

  get "/deposits/confirmation", to: "deposits#confirmation"
  post "/deposits/", to: "deposits#create"

  get "/deposits/success", to: "deposits#success"

  get "/deposits/", to: "deposits#index"

  get "*path", to: "pages#not_found", as: "page_not_found", constraints: lambda { |req|
  req.path.exclude? 'rails/active_storage'
}
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  has_one_attached :image
  has_one :deposit, through: :user

  enum gender: { Female: 0, Male: 1 }
  enum drop_off: { Yes: 0, No: 1 }

end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :listings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_many :deposits, through: :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_deposit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!  


  def index
    @deposits = Deposit.where(user_id: current_user.id).includes(listing: :user)
  end

  def new
    @deposit = Deposit.new
    @listing = Listing.find(params[:listing_id])

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user.email,
      customer_address: @deposit.address,
      line_items: [{
          name: @listing.title,
          description: @listing.description,
          amount: @listing.price*100,
          currency: 'aud',
          date: @deposit.date,
          quantity: 1
      }],
      payment_intent_data: {
          metadata: {
              user_id: current_user.id,
              listing_id: @listing.id,
              customer_address: @deposit.address,
              date: @deposit.date,
          }
      },
      success_url: "#{root_url}deposits/success?user_id=#{current_user.id}&listing_id=#{@listing.id}&amount=#{@listing.price}",
      cancel_url: "#{root_url}listings"
    )
    @session_id = session.id
  end




  def create
    @deposit = Deposit.new(deposit_params)
    if @deposit.save
      redirect_to deposits_confirmation_path(deposit: @deposit)
    end
  end

  def confirmation
    @deposit = Deposit.find(params[:deposit])
    @listing = @deposit.listing


    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user.email,
      line_items: [{
          name: @listing.title,
          description: @listing.description,
          amount: @listing.price*100,
          currency: 'aud',
          quantity: 1
      }],
      payment_intent_data: {
          metadata: {
              user_id: current_user.id,
              listing_id: @listing.id
          }
      },
      success_url: "#{root_url}deposits/success?user_id=#{current_user.id}&listing_id=#{@listing.id}&amount=#{@listing.price}&deposit_id=#{@deposit.id}",
      cancel_url: "#{root_url}listings"
    )
    @session_id = session.id
  end

  def success

    @deposit = Deposit.find(params[:deposit_id])
  end

  def webhook

    status 200
  end


  def update
    respond_to do |format|
      if @deposit.update(deposit_params)
        format.html { redirect_to @deposit, notice: 'deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit }
      else
        format.html { render :edit }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @deposit.destroy
    respond_to do |format|
      format.html { redirect_to deposits_url, notice: 'deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_deposit
    @deposit = Deposit.find(params[:id])
  end


  def deposit_params
    params.permit(:user_id, :address, :listing_id, :date)
  end  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :set_user_listing, only: [:edit, :update, :destroy]
  before_action :set_select_options, only: [:new, :edit, :update]


  def index
    @listings = Listing.all.order('updated_at DESC')
    @listings = @listings.where(skill_id: params[:skill_id]) if params[:skill_id].present?
  end


  def show
    if @listing == nil
      redirect_to page_not_found_path("page_not_found")
    end
  end

  

  def new
    @listing = Listing.new
    @listed_listings = Listing.where(user:current_user)
  end

  def edit
    puts current_user.id, @listing.user
    # authorize @listing
  end


  def create
    @listing = current_user.listings.new(listing_params)
    # byebug

      if @listing.save
        redirect_to @listing
      else
        render :new
      end

  end

  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_path, notice: "#{@listing.title} has been updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_path, notice: "#{@listing.title} has been deleted." }
      format.json { head :no_content }
    end
  end

  private
  
    def set_listing
      @listing = Listing.find_by_id(params[:id])
    end

    def set_select_options
      @select_options = []
      Skill.all.each_with_index do |skill, index| 
        @select_options.push([skill.title,index+1]) 
      end
    end 

    def listing_params
      params.require(:listing).permit(:title, :price, :description, :gender, :breed, :skill_id, :drop_off, :notes, :image, :user_id)
    end



    def set_user_listing
      id = params[:id]
      @listing = current_user.listings.find_by_id( id )

      if @listing == nil
        redirect_to listings_path
      elsif @listing.price == nil
        @listing.price = 0
      end

    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!   

  def home
  end


  def about
  end
  

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  def index
    @skills = Skill.all
  end

  def show
    @skills = Skill.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/deposits/_form.html.erb
<p><strong>NOTE</strong></p>
<p>In order to book this goat, we require a deposit of one day's rental fee. Should you require a goat for more than one day, please make overnight arrangements privately with the owner of the goat.</p>

<p>Please note, goats are subject to availability. Goats are not guaranteed for all dates.</p>
<br>

<%= form_with(model: deposit, local: true) do |form| %>
  <% if deposit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deposit.errors.count, "error") %> prohibited this deposit from being saved:</h2>
      <ul>
      <% deposit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Listing Title:</strong>
    <%= @listing.title %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= @listing.breed %> Goat
  </p>

  <p>
    <strong>Price per day:</strong>
    $<%= @listing.price %>
  </p>

<p>
  <div class="field">
    <strong>Requested <%= form.label :date %>:</strong>
    <%= form.date_field :date, value: params[:deposit_date] %>
  </div>
<p>

  <div class="field">
    <%=hidden_field_tag :user_id, current_user.id %>
  </div>

  <p><strong>Confirmation Email Address:</strong> <%=current_user.email %></p>



  <div class="field">
    <strong><%= label_tag :address %> For Service:</strong>
    <input id="autocomplete_search" name="address" form-tag=:address type="text" class="form-control" placeholder="House number, street, city, state, postcode. PLEASE NOTE we only service greater Melbourne." />
      <input type="hidden" name="lat">
      <input type="hidden" name="long">
  </div>


  <div class="field">
    <%=hidden_field_tag :listing_id, params[:listing_id] %>
  </div>

<br>


  <button type="submit" value="Submit" action="deposits/confirmation" method="post" class="btn btn-info btn-sm">Review details</button>





  <small><%= link_to "Back to #{@listing.title} ", listing_path(@listing) %></small>

<% end %>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_maps_api_key%>&amp;libraries=places"></script>
         
<script>
  google.maps.event.addDomListener(window, 'load', initialize);
    function initialize() {
      var input = document.getElementById('autocomplete_search');
      var autocomplete = new google.maps.places.Autocomplete(input);
      autocomplete.addListener('place_changed', function () {
      var place = autocomplete.getPlace();
      // place variable will have all the information you are looking for.
      $('#lat').val(place.geometry['location'].lat());
      $('#long').val(place.geometry['location'].lng());
    });
  }
</script>

app/views/deposits/confirmation.html.erb
<p>Please confirm the following details are correct before proceeding to payment.</p>

<p><strong>Your Email:</strong> <%= current_user.email %> </p>
<p><strong>Your Address:</strong> <%= @deposit.address %>
<p><strong>Chosen Goat:</strong> <%= @deposit.listing.title %> ($<%= @deposit.listing.price %> per day ) </p>


    
    
    <button type="submit" class="btn btn-info btn-sm" data-stripe="payment">
        Pay Deposit of $<%= @listing.price %>
    </button>

    <small><%= link_to 'Go Back', :back %></small>


    <script src="https://js.stripe.com/v3/"></script>

    <script>
    document
        .querySelector("[data-stripe='payment']")
        .addEventListener("click", () => {
        const stripe = Stripe(
            "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
        );
        stripe.redirectToCheckout({
            sessionId: "<%= @session_id %>"
        });
        });
    </script>

app/views/deposits/index.html.erb
<h2>Goat Rental History</h2>
<div class="container">


  <table class="table table-striped table-responsive d-xl-table">
    <thead>
      <tr>
        <th colspan="7" class="border-top-0"></th>
      </tr>
      <tr>
        <th style="min-width: 150px;">Order Number</th>
        <th style="min-width: 110px;">Listing Title</th>
        <th style="min-width: 110px;">Goat ID</th>
        <th style="min-width: 130px;">Amount Paid</th>
        <th style="min-width: 130px;">Date / Time Paid</th>
        <th style="min-width: 110px;">Owner Email</th>
      </tr>
    </thead>


  <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= deposit.created_at.to_i %></td>
        <td><%= link_to listing_path(deposit.listing ) do %>
            <%= deposit.listing.title %><% end %></td>
        <td><%= deposit.listing.id %></td>
        <td>$<%= deposit.listing.price %></td>
        <td><%= deposit.created_at %></td>
        <td><%= deposit.listing.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/deposits/new.html.erb
<%= render 'form', deposit: @deposit, listing: @listing %>

app/views/deposits/success.html.erb
<p>Thanks <strong><%= current_user.email %>,</strong><br></p>
<p>You've successfully paid <strong>$<%= @deposit.listing.price %>.<br></strong></p> 

<p>Please arrange your hire of <%= @deposit.listing.title %> by emailing <strong><%= @deposit.listing.user.email %></strong><br></p>

<p>Your address on file for delivery is <%= @deposit.address %>.<br></p>


<p>Your confirmation number is <strong><%= @deposit.created_at.to_i %></strong><br><br><br></p>




<strong><p><%= link_to "See your Rental History", deposits_path %></strong></p>

<%= link_to "Print This Page", '#', class: "btn btn-info btn-sm", 
            onclick: 'window.print();return false;' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="icon" href="/assets/favicon.png">
    <title>Jim's Goats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
This website was made by Molly Madden as a Coder Academy project to learn Ruby on Rails. The Jim's Goats branding was created using the Jim's logo generator found at <a href="https://jims.net/logogenerator/">jims.net/logogenerator.</a><br>

No business is conducted from this website. The business (and website) is purely fictitious and no goats are involved in any transactions.
  <div class="logo"><img src="/assets/jimandgoat.png" height=150></div>

  
    <nav class="text-nav">
  <div>




    
    <%= link_to "Home", root_path %>
    <%= link_to "List A Goat", new_listing_path %>
    <%= link_to "See All Goats", listings_path %>
    <%= link_to "Rental History", deposits_path %>
    <%= link_to "About", about_path %>
    <% if user_signed_in? %>
       <%= link_to('Sign Out', destroy_user_session_path, method: :delete) %>
      <% else %>
        <%= link_to('Sign In', new_user_session_path) %>
    <% end %>
    </div>
    <% if user_signed_in? %>
    <small>Logged in as <%= current_user.email %></small>
    <% end %>
    

</nav>



    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>

<!-- Load an icon library to show a hamburger menu (bars) on small screens -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</div>


  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class=formy>
  <div class="text">
    <strong><%= form.label :title %><br/></strong>
    <%= form.text_field :title, placeholder: "Goat's name?", :required => true %>
  </div><br>

  <div class="text">
    <strong><%= form.label :price %> per day <br/></strong>
    <%= form.text_field :price, :required => true, value: number_with_precision(listing.price, :precision => 2) %>
  </div><br>

  <div class="text">
    <strong><%= form.label :description %><br/>
    <%= form.text_area :description, placeholder: "Talk about your goat! Personality, star sign", :required => true %>
  </div><br>

  <div>




      <strong><%= form.label :gender %></strong>
      <a target="" href="/help" title="Only Billy Goats (male) can be Lover Goats and only Nanny Goats (female) can be Dairy Queens. By listing a goat on Jim's Goats you agree to the Terms and Conditions found here."><img src="https://shots.jotform.com/kade/Screenshots/blue_question_mark.png" height="13px"/></a><br>
      <% Listing.genders.keys.each do |gender| %>
      <%= form.label gender %>
      <%= form.radio_button :gender, gender %><p>

      <% if gender == listing.gender %>
      <% form.radio_button :gender, :checked => true %>    
</p>
      <% end %>
      <% end %>
  </div><br>

  <div class="text">
  <strong><%= form.label :breed %><br/></strong>
  <%= form.text_field :breed %>
  </div><br>

  <div class="text">
  <strong>Special
    <%= form.label :skill_id %><br/></strong>
    <%= form.select :skill_id, options_for_select( Skill.all.collect { |u| [u.title, u.id] }, :selected => listing.skill_id )%>
    <a target="" href="/help" title="Only Billy Goats (male) can be Lover Goats and only Nanny Goats (female) can be Dairy Queens. By listing a goat on Jim's Goats you agree to the Terms and Conditions found here."><img src="https://shots.jotform.com/kade/Screenshots/blue_question_mark.png" height="13px"/></a>
  </div><br>


  <div>
      <strong><%= form.label :drop_off %> available? <br></strong>
    <% Listing.drop_offs.keys.each do |drop_off| %>
      <%= form.label drop_off %>
      <%= form.radio_button :drop_off, drop_off %><p>

      <% if drop_off == listing.drop_off %>
      <% form.radio_button :drop_off, :checked => true %>
      <% end %></p>
      <% end %>
  </div><br>

  <div class="text">
    <strong><%= form.label :notes %><br/></strong>
    <%= form.text_area :notes, placeholder: "Favourite treats, good with kids & pets, etc" %>
  </div><br>


  <div class="text">
    <strong><%= form.label :image %><br/></strong>
    <%= form.file_field :image, accept: 'image/png, image/gif, image/jpg, image/jpeg' %>
  </div>


  <br>
  <div>
    <%= form.submit class: "btn btn-info btn-sm"%>
  </div>
  </div>

<% end %>

app/views/listings/edit.html.erb
<div class= "bg4">
</div>
<div class="sell-form-styles">
<h1>Edit</h1>
<div class="subtext">Edit Listing:</div>
<br/>
<%= render 'form', listing: @listing %>


</div>
</div>
</div>

app/views/listings/failure.html.erb
you do not have permission to edit this file

app/views/listings/help.html.erb
TERMS AND CONDITIONS

Goat safety is paramount above all else. Please see below terms of goat rental based on special skill.

<div class="card-group">
  <div class="card">

    <img src="/assets/yoga.jpg" class="card-img-top">
    <div class="card-body text-center">
      <p class="card-title">Our Yoga Master goats are pracitioners of the ancient art of Vinyāsa, bringing you peace and mindfulness as you burn calories.</p>
    </div>

    </div>
  <div class="card">

    <img src="/assets/milking.jpg" class="card-img-top">
    <div class="card-body text-center">
      <p class="card-title">Our Dairy Queens are nanny goats who are currently producing milk. We do not allow goats to be Dairy Queens unless their young are healthy & are currently receiving sufficient sustenance. A nanny goat can only be listed as a Dairy Queen once in any 12 month period to discourage overbreeding.</p>
    </div>

</div>

  <div class="card">

    <img src="/assets/love.jpg" class="card-img-top">
    <div class="card-body text-center">
      <p class="card-title">Our Lover Goats are male only, and are regularly tested and confirmed free of disease. These billy goats come from pedigree blood lines to ensure healthy young. Inbreeding is strictly prohibited as per these terms and conditions of Jim's Goats.</p>
    </div>

      </div>

  <div class="card">

    <img src="/assets/companionship.jpg" class="card-img-top">
    <div class="card-body text-center">
      <p class="card-title">Our Cuddly Companions are goats that are children and pet friendly, who are highly socialised among humans and house broken.</p>
    </div>

  </div>
</div>

app/views/listings/index.html.erb
<% if user_signed_in? %>
<p class="text-warning">★ your goat</p><br>
<% else %>
<br>
<% end %>

  <%= form_tag listings_path, :method => 'get' do %>
   <%= select_tag(:skill_id, options_for_select(Skill.order(:title).pluck(:title, :id) ,:selected =>params[:option]), onchange: 'this.form.submit();', class: "form-control custom-select", prompt: "All goats are Garden Gurus, but some of our goats have extra special skills! Click here to filter by area of expertise.", include_blank: "Show All")%>
  <% end %>
 


<div class="group">

  <% @listings.each do |listing| %>
    


<div class="w3card">
<div class="piccy">
  <%= link_to listing_path( listing ) do %>
    <%=image_tag(listing.image, height: 200, width: 280) %><% end %></div>
  <div class="container">
    <h4><b><%= link_to listing_path( listing ) do %>
        <%= listing.title %><% end %></b></h4>
        <%= listing.breed %> Goat<br>
         $<%= listing.price %> per day<br>
   <small>Special Skill: <%= listing.skill.title %></small>
      <% if user_signed_in? %>
      <% if current_user.id == listing.user_id %>
      <p class="text-warning">★</p>
      <% end %>         
      <% end %> 



  </div>
</div>




  <% end %>

</div>

app/views/listings/new.html.erb
<div class="bg4">
  </div>
      <div class="listing-form-styles">
      <div class="subtext"> <h2>List a new goat</h2> </div>
        <%= render 'form', listing: @listing %>
        <br>
      </div>


  </div>
</div>

app/views/listings/show.html.erb
<%#= link_to "Edit", edit_listing_path( @listing ) %>
<%#= link_to "Back", listings_path %>

<div class="card mb-3" style="max-width: 100vw;">

    <% if current_user.id == @listing.user_id %>
    <div class="alert alert-danger">This is your goat</div>
    <% end %>
  <div class="row no-gutters">
        <div class="col-md-4">
            <div class="cardy">
            <%= image_tag @listing.image, class:"card-img" %>
            </div>
        </div>


        <div class="card-body">
        <h5 class="card-title"><h1><%= @listing.title %></h1></h5>
            <p class="card-text">
            
            <p>
            <strong>Description:</strong>
            <%= @listing.description %></p>

            <p>
            <strong>Price:</strong>
            <%= number_to_currency(@listing.price) %> per day</p>

            <p>
            <strong>Gender:</strong>
            <%= @listing.gender %></p>

            <p>
            <strong>Breed:</strong>
            <%= @listing.breed %>
            </p>

            <p>
            <strong>Drop off available?</strong>
            <%= @listing.drop_off %></p>

            <p>
            <strong>Notes:</strong>
            <%= @listing.notes %></p>

            <p>
            <strong>Special Skill:</strong>
            <%= @listing.skill.title %></p>

            <p>
            <strong>Owned By:</strong>
            <%= @listing.user.email %></p></small></p>

            <% if current_user.id == @listing.user_id %>
            <% else %>
            <%= link_to 'Book Goat', new_listing_deposit_path(@listing), class: "btn btn-info btn-sm"%>
            <% end %>
            <small><%= link_to "Back to all goats", listings_path %></small>

    </div>


</div>

        <% if current_user.id == @listing.user_id %>
            <%= link_to "Edit |", edit_listing_path( @listing ) %>
            <%= link_to "| Delete", listing_path( @listing ) , method: :delete, data: {confirm: 'Are you super sure?'} %>
        <% end %>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>

<p class="paragraph">Jim's Goats have been serving Melbourne since 2007, when we first saw an opportunity to utilise Goats, one of the cutest and most versatile animals in Australia. With an increasing population in inner city suburbs, garage ownership and storage solutions are harder to come by. There is also the pesky problem of noise pollution; how does a renter in Fitzroy maintain their garden patch whilst keeping their neighbours happy when they cannot afford a lawnmower nor store it? Simple! Rent a goat!</p>

Goat safety is paramount above all else. Please see below details based on skill category.

<div class="card-group">
  <div class="card">

    <img src="/assets/yoga.jpg" class="card-img-top">
    <div class="card-body text-center">
      <p class="card-title">Our Yoga Master goats are pracitioners of the ancient art of Vinyāsa, bringing you peace and mindfulness as you burn calories.</p>
    </div>

    </div>
  <div class="card">

    <img src="/assets/milking.jpg" class="card-img-top">
    <div class="card-body text-center">
      <p class="card-title">Our Dairy Queens are nanny goats who are currently producing milk. We do not allow goats to be Dairy Queens unless their young are healthy & are currently receiving sufficient sustenance. A nanny goat can only be listed as a Dairy Queen once in any 12 month period to discourage overbreeding.</p>
    </div>

</div>

  <div class="card">

    <img src="/assets/love.jpg" class="card-img-top">
    <div class="card-body text-center">
      <p class="card-title">Our Lover Goats are male only, and are regularly tested and confirmed free of disease. These billy goats come from pedigree blood lines to ensure healthy young. Inbreeding is strictly prohibited as per these terms and conditions of Jim's Goats.</p>
    </div>

      </div>

  <div class="card">

    <img src="/assets/companionship.jpg" class="card-img-top">
    <div class="card-body text-center">
      <p class="card-title">Our Cuddly Companions are goats that are children and pet friendly, who are highly socialised among humans and house broken.</p>
    </div>

  </div>
</div>



    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  </head>

  <body>


  <div class="card-group">
    <div class="card">
      <div class="card-body text-center">
      <h5 class="card-title"><%= link_to "I need a goat", listings_path %></h5>
      <%= link_to listings_path do %>
      <img src="/assets/bleet.jpg" class="card-img-top">
      <% end %>    
    </div>
  </div>

  <div class="card">
    <div class="card-body text-center">
    <h5 class="card-title"><%= link_to "I have a goat", new_listing_path %></h5>
    <%= link_to new_listing_path do %>
    <img src="/assets/lawnmowing.jpg" class="card-img-top">
  </div>
    <% end %>
  </div>
  </div>


    <%= yield %>
  </body>
</html>

app/views/pages/not_found.html.erb
<style>
  .card {
    margin: auto;
    border: none;
    }
</style>

<div class="card w-75">

  <div class="card-body" >
    <h5 class="card-title">Page Not Found</h5>
  </div>
  <img class="card-img-bottom" src="/assets/smizey.jpg" alt="Card image cap">

</div>

    

app/views/payments/success.html.erb
Thanks <%= current_user.email %>,<br>
You've successfully paid <%= number_to_currency(@listing.price) %> to <%= @listing.user.email %> <br> 

Please arrange your hire of <%= @listing.title %> by emailing <%= @listing.user.email %> <br>


<p><%= link_to "Go to listings", listings_path %></p>